version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/session2/java/UserApp"
    schedule:
      interval: "daily"
    labels:
      - dependencies
      - automerge
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"