name: .NET 8 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore session1/dotnet/ProductService.Tests/ProductService.Tests.csproj

      - name: Build
        run: dotnet build session1/dotnet/ProductService.Tests/ProductService.Tests.csproj --no-restore --configuration Release

      - name: Run all tests
        run: dotnet test session1/dotnet/ProductService.Tests/ProductService.Tests.csproj --no-build --configuration Release --verbosity normal
