name: UserApp CI

on:
  push:
    paths:
      - 'session2/java/**'
  pull_request:
    paths:
      - 'session2/java/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --batch-mode
        working-directory: session2/java/UserApp